# Generated by Django 4.1.13 on 2024-03-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('loginpassword', models.CharField(max_length=100)),
                ('confirmpassword', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=12)),
                ('verificationcode', models.CharField(blank=True, default=None, max_length=6, null=True)),
                ('reset_password_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('token', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('refresh_token', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'loginapp_userdetails',
            },
        ),
    ]
