# Generated by Django 4.1.13 on 2024-03-13 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
