# Generated by Django 4.1.13 on 2024-03-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_remove_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='user',
            table='userdetails',
        ),
    ]
